site_name: Uni notes

repo_url: https://github.com/s0ko1ex/uni-notes
repo_name: s0ko1ex/Uni-notes

nav:
  - Главная страница: 'index.md'
  - 6й семестр:
    - '6th_semester/index.md'
    - Математическая логика и логическое программирование:
      - '6th_semester/mlilp/index.md'
    - Безопасность компьютерных систем:
      - '6th_semester/systemsec/index.md'
    - Практикум на ЭВМ:
      - '6th_semester/cspractice/index.md'
    - Методы машинного обучения:
      - '6th_semester/mml/index.md'
    - Оптимальное управление:
      - '6th_semester/om/index.md'
    - Численные методы:
      - '6th_semester/nummeth/index.md'
    - Математические основы криптологии:
      - '6th_semester/mbc/index.md'
    - Случайные процессы:
      - '6th_semester/randproc/index.md'
    - Методы оптимизации:
      - '6th_semester/methopt/index.md'
    - Архитектура и процесс разработки ПО:
      - '6th_semester/pppoc/index.md'
      - Экзамен:
        - Вопрос 1:
          - '6th_semester/pppoc/exam/question_08/index.md'
  - 7й семестр:
    - '7th_semester/index.md'
    - Базы данных:
      - '7th_semester/db/index.md'
    - Криптопротоколы:
      - '7th_semester/crypto/index.md'
    - Дополнительные главы дискретной математики и кибернетики:
      - '7th_semester/discrete_math/index.md'
    - Теория игр и исследование операций:
      - '7th_semester/game_theory/index.md'
    - Математическая теория анализа программ:
      - '7th_semester/program_analyses/index.md'
    - Суперкомпьютеры и параллельная обработка данных:
      - '7th_semester/supercomputer/index.md'
    - Глубокое машинное обучение:
      - '7th_semester/dl/index.md'
    - Математические модели в экономике:
      - '7th_semester/economics/index.md'
    - Введение в теорию сложности вычислений:
      - '7th_semester/alg_complexity/index.md'

theme:
  name: material
  language: ru

  icon:
    logo: octicons/book-16
    repo: fontawesome/brands/github

  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode

    - scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.indexes
    - navigation.instant

plugins:
  - search:
      lang:
        - en
        - ru
  - tags

markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - attr_list

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js